### ISSUE TITLE
Crash when I clicked "search" button

### ISSUE THREAD

**Issue by samoylenkodmitry** [dotanuki-labs/norris#50]
Steps to reproduce:
1. Emulator API 30
2. Open and run project build
3. Click "search" icon when app is ready

`2021-01-24 20:07:22.019 6280-6280/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.dotanuki.demos.norris.debug, PID: 6280
    java.lang.IllegalStateException: LifecycleOwner io.dotanuki.norris.facts.FactsActivity@807bd3e is attempting to register while current state is RESUMED. LifecycleOwners must call register before they are STARTED.
        at androidx.activity.result.ActivityResultRegistry.register(ActivityResultRegistry.java:120)
        at androidx.activity.ComponentActivity.registerForActivityResult(ComponentActivity.java:666)
        at androidx.activity.ComponentActivity.registerForActivityResult(ComponentActivity.java:675)
        at io.dotanuki.norris.navigator.Navigator.navigateForResult(Navigator.kt:21)
        at io.dotanuki.norris.facts.FactsActivity.goToSearch(FactsActivity.kt:70)
        at io.dotanuki.norris.facts.FactsActivity.onOptionsItemSelected(FactsActivity.kt:62)
`

**Comment by ubiratansoares** [comment]
Hi @samoylenkodmitry ! Thanks for reporting.

That bug will go away as soon as refactor the navigation system with a proper implementation on top of deep-links. I will let you know as soon as I have time to work on this
